package entry;

public class ManageRoleFuncRel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manage_role_func_rel.manage_role_func_rel_id
     *
     * @mbggenerated
     */
    private Long manageRoleFuncRelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manage_role_func_rel.manage_role_id
     *
     * @mbggenerated
     */
    private Long manageRoleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manage_role_func_rel.manage_func_id
     *
     * @mbggenerated
     */
    private Long manageFuncId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manage_role_func_rel.is_delete
     *
     * @mbggenerated
     */
    private Integer isDelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manage_role_func_rel.create_time
     *
     * @mbggenerated
     */
    private Long createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manage_role_func_rel.modify_time
     *
     * @mbggenerated
     */
    private Long modifyTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manage_role_func_rel.manage_role_func_rel_id
     *
     * @return the value of manage_role_func_rel.manage_role_func_rel_id
     *
     * @mbggenerated
     */
    public Long getManageRoleFuncRelId() {
        return manageRoleFuncRelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manage_role_func_rel.manage_role_func_rel_id
     *
     * @param manageRoleFuncRelId the value for manage_role_func_rel.manage_role_func_rel_id
     *
     * @mbggenerated
     */
    public void setManageRoleFuncRelId(Long manageRoleFuncRelId) {
        this.manageRoleFuncRelId = manageRoleFuncRelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manage_role_func_rel.manage_role_id
     *
     * @return the value of manage_role_func_rel.manage_role_id
     *
     * @mbggenerated
     */
    public Long getManageRoleId() {
        return manageRoleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manage_role_func_rel.manage_role_id
     *
     * @param manageRoleId the value for manage_role_func_rel.manage_role_id
     *
     * @mbggenerated
     */
    public void setManageRoleId(Long manageRoleId) {
        this.manageRoleId = manageRoleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manage_role_func_rel.manage_func_id
     *
     * @return the value of manage_role_func_rel.manage_func_id
     *
     * @mbggenerated
     */
    public Long getManageFuncId() {
        return manageFuncId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manage_role_func_rel.manage_func_id
     *
     * @param manageFuncId the value for manage_role_func_rel.manage_func_id
     *
     * @mbggenerated
     */
    public void setManageFuncId(Long manageFuncId) {
        this.manageFuncId = manageFuncId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manage_role_func_rel.is_delete
     *
     * @return the value of manage_role_func_rel.is_delete
     *
     * @mbggenerated
     */
    public Integer getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manage_role_func_rel.is_delete
     *
     * @param isDelete the value for manage_role_func_rel.is_delete
     *
     * @mbggenerated
     */
    public void setIsDelete(Integer isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manage_role_func_rel.create_time
     *
     * @return the value of manage_role_func_rel.create_time
     *
     * @mbggenerated
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manage_role_func_rel.create_time
     *
     * @param createTime the value for manage_role_func_rel.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manage_role_func_rel.modify_time
     *
     * @return the value of manage_role_func_rel.modify_time
     *
     * @mbggenerated
     */
    public Long getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manage_role_func_rel.modify_time
     *
     * @param modifyTime the value for manage_role_func_rel.modify_time
     *
     * @mbggenerated
     */
    public void setModifyTime(Long modifyTime) {
        this.modifyTime = modifyTime;
    }
}