package entry;

public class ManageSystem {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manage_system.manage_system_id
     *
     * @mbggenerated
     */
    private Long manageSystemId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manage_system.system_name
     *
     * @mbggenerated
     */
    private String systemName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manage_system.client_id
     *
     * @mbggenerated
     */
    private String clientId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manage_system.client_secret
     *
     * @mbggenerated
     */
    private String clientSecret;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manage_system.redirect_uri
     *
     * @mbggenerated
     */
    private String redirectUri;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manage_system.is_delete
     *
     * @mbggenerated
     */
    private Integer isDelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manage_system.create_time
     *
     * @mbggenerated
     */
    private Long createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manage_system.modify_time
     *
     * @mbggenerated
     */
    private Long modifyTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manage_system.manage_system_id
     *
     * @return the value of manage_system.manage_system_id
     *
     * @mbggenerated
     */
    public Long getManageSystemId() {
        return manageSystemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manage_system.manage_system_id
     *
     * @param manageSystemId the value for manage_system.manage_system_id
     *
     * @mbggenerated
     */
    public void setManageSystemId(Long manageSystemId) {
        this.manageSystemId = manageSystemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manage_system.system_name
     *
     * @return the value of manage_system.system_name
     *
     * @mbggenerated
     */
    public String getSystemName() {
        return systemName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manage_system.system_name
     *
     * @param systemName the value for manage_system.system_name
     *
     * @mbggenerated
     */
    public void setSystemName(String systemName) {
        this.systemName = systemName == null ? null : systemName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manage_system.client_id
     *
     * @return the value of manage_system.client_id
     *
     * @mbggenerated
     */
    public String getClientId() {
        return clientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manage_system.client_id
     *
     * @param clientId the value for manage_system.client_id
     *
     * @mbggenerated
     */
    public void setClientId(String clientId) {
        this.clientId = clientId == null ? null : clientId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manage_system.client_secret
     *
     * @return the value of manage_system.client_secret
     *
     * @mbggenerated
     */
    public String getClientSecret() {
        return clientSecret;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manage_system.client_secret
     *
     * @param clientSecret the value for manage_system.client_secret
     *
     * @mbggenerated
     */
    public void setClientSecret(String clientSecret) {
        this.clientSecret = clientSecret == null ? null : clientSecret.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manage_system.redirect_uri
     *
     * @return the value of manage_system.redirect_uri
     *
     * @mbggenerated
     */
    public String getRedirectUri() {
        return redirectUri;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manage_system.redirect_uri
     *
     * @param redirectUri the value for manage_system.redirect_uri
     *
     * @mbggenerated
     */
    public void setRedirectUri(String redirectUri) {
        this.redirectUri = redirectUri == null ? null : redirectUri.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manage_system.is_delete
     *
     * @return the value of manage_system.is_delete
     *
     * @mbggenerated
     */
    public Integer getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manage_system.is_delete
     *
     * @param isDelete the value for manage_system.is_delete
     *
     * @mbggenerated
     */
    public void setIsDelete(Integer isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manage_system.create_time
     *
     * @return the value of manage_system.create_time
     *
     * @mbggenerated
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manage_system.create_time
     *
     * @param createTime the value for manage_system.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manage_system.modify_time
     *
     * @return the value of manage_system.modify_time
     *
     * @mbggenerated
     */
    public Long getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manage_system.modify_time
     *
     * @param modifyTime the value for manage_system.modify_time
     *
     * @mbggenerated
     */
    public void setModifyTime(Long modifyTime) {
        this.modifyTime = modifyTime;
    }
}