package entry;

public class ManageGroup {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manage_group.manage_group_id
     *
     * @mbggenerated
     */
    private Long manageGroupId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manage_group.parent_id
     *
     * @mbggenerated
     */
    private Long parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manage_group.group_name
     *
     * @mbggenerated
     */
    private String groupName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manage_group.show_order
     *
     * @mbggenerated
     */
    private Integer showOrder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manage_group.is_delete
     *
     * @mbggenerated
     */
    private Integer isDelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manage_group.create_time
     *
     * @mbggenerated
     */
    private Long createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manage_group.modify_time
     *
     * @mbggenerated
     */
    private Long modifyTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manage_group.manage_group_id
     *
     * @return the value of manage_group.manage_group_id
     *
     * @mbggenerated
     */
    public Long getManageGroupId() {
        return manageGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manage_group.manage_group_id
     *
     * @param manageGroupId the value for manage_group.manage_group_id
     *
     * @mbggenerated
     */
    public void setManageGroupId(Long manageGroupId) {
        this.manageGroupId = manageGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manage_group.parent_id
     *
     * @return the value of manage_group.parent_id
     *
     * @mbggenerated
     */
    public Long getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manage_group.parent_id
     *
     * @param parentId the value for manage_group.parent_id
     *
     * @mbggenerated
     */
    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manage_group.group_name
     *
     * @return the value of manage_group.group_name
     *
     * @mbggenerated
     */
    public String getGroupName() {
        return groupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manage_group.group_name
     *
     * @param groupName the value for manage_group.group_name
     *
     * @mbggenerated
     */
    public void setGroupName(String groupName) {
        this.groupName = groupName == null ? null : groupName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manage_group.show_order
     *
     * @return the value of manage_group.show_order
     *
     * @mbggenerated
     */
    public Integer getShowOrder() {
        return showOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manage_group.show_order
     *
     * @param showOrder the value for manage_group.show_order
     *
     * @mbggenerated
     */
    public void setShowOrder(Integer showOrder) {
        this.showOrder = showOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manage_group.is_delete
     *
     * @return the value of manage_group.is_delete
     *
     * @mbggenerated
     */
    public Integer getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manage_group.is_delete
     *
     * @param isDelete the value for manage_group.is_delete
     *
     * @mbggenerated
     */
    public void setIsDelete(Integer isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manage_group.create_time
     *
     * @return the value of manage_group.create_time
     *
     * @mbggenerated
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manage_group.create_time
     *
     * @param createTime the value for manage_group.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manage_group.modify_time
     *
     * @return the value of manage_group.modify_time
     *
     * @mbggenerated
     */
    public Long getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manage_group.modify_time
     *
     * @param modifyTime the value for manage_group.modify_time
     *
     * @mbggenerated
     */
    public void setModifyTime(Long modifyTime) {
        this.modifyTime = modifyTime;
    }
}