package entry;

public class ManageUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manage_user.manage_user_id
     *
     * @mbggenerated
     */
    private Long manageUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manage_user.user_name
     *
     * @mbggenerated
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manage_user.user_pwd
     *
     * @mbggenerated
     */
    private String userPwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manage_user.real_name
     *
     * @mbggenerated
     */
    private String realName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manage_user.phone
     *
     * @mbggenerated
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manage_user.email
     *
     * @mbggenerated
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manage_user.is_delete
     *
     * @mbggenerated
     */
    private Integer isDelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manage_user.create_time
     *
     * @mbggenerated
     */
    private Long createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manage_user.modify_time
     *
     * @mbggenerated
     */
    private Long modifyTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manage_user.manage_user_id
     *
     * @return the value of manage_user.manage_user_id
     *
     * @mbggenerated
     */
    public Long getManageUserId() {
        return manageUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manage_user.manage_user_id
     *
     * @param manageUserId the value for manage_user.manage_user_id
     *
     * @mbggenerated
     */
    public void setManageUserId(Long manageUserId) {
        this.manageUserId = manageUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manage_user.user_name
     *
     * @return the value of manage_user.user_name
     *
     * @mbggenerated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manage_user.user_name
     *
     * @param userName the value for manage_user.user_name
     *
     * @mbggenerated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manage_user.user_pwd
     *
     * @return the value of manage_user.user_pwd
     *
     * @mbggenerated
     */
    public String getUserPwd() {
        return userPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manage_user.user_pwd
     *
     * @param userPwd the value for manage_user.user_pwd
     *
     * @mbggenerated
     */
    public void setUserPwd(String userPwd) {
        this.userPwd = userPwd == null ? null : userPwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manage_user.real_name
     *
     * @return the value of manage_user.real_name
     *
     * @mbggenerated
     */
    public String getRealName() {
        return realName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manage_user.real_name
     *
     * @param realName the value for manage_user.real_name
     *
     * @mbggenerated
     */
    public void setRealName(String realName) {
        this.realName = realName == null ? null : realName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manage_user.phone
     *
     * @return the value of manage_user.phone
     *
     * @mbggenerated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manage_user.phone
     *
     * @param phone the value for manage_user.phone
     *
     * @mbggenerated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manage_user.email
     *
     * @return the value of manage_user.email
     *
     * @mbggenerated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manage_user.email
     *
     * @param email the value for manage_user.email
     *
     * @mbggenerated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manage_user.is_delete
     *
     * @return the value of manage_user.is_delete
     *
     * @mbggenerated
     */
    public Integer getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manage_user.is_delete
     *
     * @param isDelete the value for manage_user.is_delete
     *
     * @mbggenerated
     */
    public void setIsDelete(Integer isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manage_user.create_time
     *
     * @return the value of manage_user.create_time
     *
     * @mbggenerated
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manage_user.create_time
     *
     * @param createTime the value for manage_user.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manage_user.modify_time
     *
     * @return the value of manage_user.modify_time
     *
     * @mbggenerated
     */
    public Long getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manage_user.modify_time
     *
     * @param modifyTime the value for manage_user.modify_time
     *
     * @mbggenerated
     */
    public void setModifyTime(Long modifyTime) {
        this.modifyTime = modifyTime;
    }
}