package cn.zxf.self.entry;

public class AccountInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_info.account_id
     *
     * @mbggenerated
     */
    private Integer accountId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_info.account_name
     *
     * @mbggenerated
     */
    private String accountName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_info.account_password
     *
     * @mbggenerated
     */
    private String accountPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_info.use_flag
     *
     * @mbggenerated
     */
    private Integer useFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_info.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_info.account_id
     *
     * @return the value of account_info.account_id
     *
     * @mbggenerated
     */
    public Integer getAccountId() {
        return accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_info.account_id
     *
     * @param accountId the value for account_info.account_id
     *
     * @mbggenerated
     */
    public void setAccountId(Integer accountId) {
        this.accountId = accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_info.account_name
     *
     * @return the value of account_info.account_name
     *
     * @mbggenerated
     */
    public String getAccountName() {
        return accountName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_info.account_name
     *
     * @param accountName the value for account_info.account_name
     *
     * @mbggenerated
     */
    public void setAccountName(String accountName) {
        this.accountName = accountName == null ? null : accountName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_info.account_password
     *
     * @return the value of account_info.account_password
     *
     * @mbggenerated
     */
    public String getAccountPassword() {
        return accountPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_info.account_password
     *
     * @param accountPassword the value for account_info.account_password
     *
     * @mbggenerated
     */
    public void setAccountPassword(String accountPassword) {
        this.accountPassword = accountPassword == null ? null : accountPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_info.use_flag
     *
     * @return the value of account_info.use_flag
     *
     * @mbggenerated
     */
    public Integer getUseFlag() {
        return useFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_info.use_flag
     *
     * @param useFlag the value for account_info.use_flag
     *
     * @mbggenerated
     */
    public void setUseFlag(Integer useFlag) {
        this.useFlag = useFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_info.user_id
     *
     * @return the value of account_info.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_info.user_id
     *
     * @param userId the value for account_info.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
}