package cn.zxf.self.entry;

public class ManageFunc {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manage_func.manage_func_id
     *
     * @mbggenerated
     */
    private Long manageFuncId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manage_func.manage_system_id
     *
     * @mbggenerated
     */
    private Long manageSystemId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manage_func.parent_id
     *
     * @mbggenerated
     */
    private Long parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manage_func.func_name
     *
     * @mbggenerated
     */
    private String funcName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manage_func.url
     *
     * @mbggenerated
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manage_func.show_order
     *
     * @mbggenerated
     */
    private Integer showOrder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manage_func.func_type
     *
     * @mbggenerated
     */
    private Integer funcType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manage_func.is_delete
     *
     * @mbggenerated
     */
    private Integer isDelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manage_func.create_time
     *
     * @mbggenerated
     */
    private Long createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manage_func.modify_time
     *
     * @mbggenerated
     */
    private Long modifyTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manage_func.manage_func_id
     *
     * @return the value of manage_func.manage_func_id
     *
     * @mbggenerated
     */
    public Long getManageFuncId() {
        return manageFuncId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manage_func.manage_func_id
     *
     * @param manageFuncId the value for manage_func.manage_func_id
     *
     * @mbggenerated
     */
    public void setManageFuncId(Long manageFuncId) {
        this.manageFuncId = manageFuncId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manage_func.manage_system_id
     *
     * @return the value of manage_func.manage_system_id
     *
     * @mbggenerated
     */
    public Long getManageSystemId() {
        return manageSystemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manage_func.manage_system_id
     *
     * @param manageSystemId the value for manage_func.manage_system_id
     *
     * @mbggenerated
     */
    public void setManageSystemId(Long manageSystemId) {
        this.manageSystemId = manageSystemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manage_func.parent_id
     *
     * @return the value of manage_func.parent_id
     *
     * @mbggenerated
     */
    public Long getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manage_func.parent_id
     *
     * @param parentId the value for manage_func.parent_id
     *
     * @mbggenerated
     */
    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manage_func.func_name
     *
     * @return the value of manage_func.func_name
     *
     * @mbggenerated
     */
    public String getFuncName() {
        return funcName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manage_func.func_name
     *
     * @param funcName the value for manage_func.func_name
     *
     * @mbggenerated
     */
    public void setFuncName(String funcName) {
        this.funcName = funcName == null ? null : funcName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manage_func.url
     *
     * @return the value of manage_func.url
     *
     * @mbggenerated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manage_func.url
     *
     * @param url the value for manage_func.url
     *
     * @mbggenerated
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manage_func.show_order
     *
     * @return the value of manage_func.show_order
     *
     * @mbggenerated
     */
    public Integer getShowOrder() {
        return showOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manage_func.show_order
     *
     * @param showOrder the value for manage_func.show_order
     *
     * @mbggenerated
     */
    public void setShowOrder(Integer showOrder) {
        this.showOrder = showOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manage_func.func_type
     *
     * @return the value of manage_func.func_type
     *
     * @mbggenerated
     */
    public Integer getFuncType() {
        return funcType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manage_func.func_type
     *
     * @param funcType the value for manage_func.func_type
     *
     * @mbggenerated
     */
    public void setFuncType(Integer funcType) {
        this.funcType = funcType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manage_func.is_delete
     *
     * @return the value of manage_func.is_delete
     *
     * @mbggenerated
     */
    public Integer getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manage_func.is_delete
     *
     * @param isDelete the value for manage_func.is_delete
     *
     * @mbggenerated
     */
    public void setIsDelete(Integer isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manage_func.create_time
     *
     * @return the value of manage_func.create_time
     *
     * @mbggenerated
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manage_func.create_time
     *
     * @param createTime the value for manage_func.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manage_func.modify_time
     *
     * @return the value of manage_func.modify_time
     *
     * @mbggenerated
     */
    public Long getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manage_func.modify_time
     *
     * @param modifyTime the value for manage_func.modify_time
     *
     * @mbggenerated
     */
    public void setModifyTime(Long modifyTime) {
        this.modifyTime = modifyTime;
    }
}