package cn.zxf.self.entry;

public class ManageUserRoleRel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manage_user_role_rel.manage_user_role_rel_id
     *
     * @mbggenerated
     */
    private Long manageUserRoleRelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manage_user_role_rel.manage_user_id
     *
     * @mbggenerated
     */
    private Long manageUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manage_user_role_rel.manage_role_id
     *
     * @mbggenerated
     */
    private Long manageRoleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manage_user_role_rel.is_delete
     *
     * @mbggenerated
     */
    private Integer isDelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manage_user_role_rel.create_time
     *
     * @mbggenerated
     */
    private Long createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manage_user_role_rel.modify_time
     *
     * @mbggenerated
     */
    private Long modifyTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manage_user_role_rel.manage_user_role_rel_id
     *
     * @return the value of manage_user_role_rel.manage_user_role_rel_id
     *
     * @mbggenerated
     */
    public Long getManageUserRoleRelId() {
        return manageUserRoleRelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manage_user_role_rel.manage_user_role_rel_id
     *
     * @param manageUserRoleRelId the value for manage_user_role_rel.manage_user_role_rel_id
     *
     * @mbggenerated
     */
    public void setManageUserRoleRelId(Long manageUserRoleRelId) {
        this.manageUserRoleRelId = manageUserRoleRelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manage_user_role_rel.manage_user_id
     *
     * @return the value of manage_user_role_rel.manage_user_id
     *
     * @mbggenerated
     */
    public Long getManageUserId() {
        return manageUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manage_user_role_rel.manage_user_id
     *
     * @param manageUserId the value for manage_user_role_rel.manage_user_id
     *
     * @mbggenerated
     */
    public void setManageUserId(Long manageUserId) {
        this.manageUserId = manageUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manage_user_role_rel.manage_role_id
     *
     * @return the value of manage_user_role_rel.manage_role_id
     *
     * @mbggenerated
     */
    public Long getManageRoleId() {
        return manageRoleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manage_user_role_rel.manage_role_id
     *
     * @param manageRoleId the value for manage_user_role_rel.manage_role_id
     *
     * @mbggenerated
     */
    public void setManageRoleId(Long manageRoleId) {
        this.manageRoleId = manageRoleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manage_user_role_rel.is_delete
     *
     * @return the value of manage_user_role_rel.is_delete
     *
     * @mbggenerated
     */
    public Integer getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manage_user_role_rel.is_delete
     *
     * @param isDelete the value for manage_user_role_rel.is_delete
     *
     * @mbggenerated
     */
    public void setIsDelete(Integer isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manage_user_role_rel.create_time
     *
     * @return the value of manage_user_role_rel.create_time
     *
     * @mbggenerated
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manage_user_role_rel.create_time
     *
     * @param createTime the value for manage_user_role_rel.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manage_user_role_rel.modify_time
     *
     * @return the value of manage_user_role_rel.modify_time
     *
     * @mbggenerated
     */
    public Long getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manage_user_role_rel.modify_time
     *
     * @param modifyTime the value for manage_user_role_rel.modify_time
     *
     * @mbggenerated
     */
    public void setModifyTime(Long modifyTime) {
        this.modifyTime = modifyTime;
    }
}