package cn.zxf.self.entry;

public class OrderRecipesRel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_recipes_rel.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_recipes_rel.order_id
     *
     * @mbggenerated
     */
    private Long orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_recipes_rel.recipes_id
     *
     * @mbggenerated
     */
    private Integer recipesId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_recipes_rel.cook_id
     *
     * @mbggenerated
     */
    private Long cookId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_recipes_rel.waiter_id
     *
     * @mbggenerated
     */
    private Long waiterId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_recipes_rel.takeaway_id
     *
     * @mbggenerated
     */
    private Integer takeawayId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_recipes_rel.rel_status
     *
     * @mbggenerated
     */
    private String relStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_recipes_rel.id
     *
     * @return the value of order_recipes_rel.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_recipes_rel.id
     *
     * @param id the value for order_recipes_rel.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_recipes_rel.order_id
     *
     * @return the value of order_recipes_rel.order_id
     *
     * @mbggenerated
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_recipes_rel.order_id
     *
     * @param orderId the value for order_recipes_rel.order_id
     *
     * @mbggenerated
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_recipes_rel.recipes_id
     *
     * @return the value of order_recipes_rel.recipes_id
     *
     * @mbggenerated
     */
    public Integer getRecipesId() {
        return recipesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_recipes_rel.recipes_id
     *
     * @param recipesId the value for order_recipes_rel.recipes_id
     *
     * @mbggenerated
     */
    public void setRecipesId(Integer recipesId) {
        this.recipesId = recipesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_recipes_rel.cook_id
     *
     * @return the value of order_recipes_rel.cook_id
     *
     * @mbggenerated
     */
    public Long getCookId() {
        return cookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_recipes_rel.cook_id
     *
     * @param cookId the value for order_recipes_rel.cook_id
     *
     * @mbggenerated
     */
    public void setCookId(Long cookId) {
        this.cookId = cookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_recipes_rel.waiter_id
     *
     * @return the value of order_recipes_rel.waiter_id
     *
     * @mbggenerated
     */
    public Long getWaiterId() {
        return waiterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_recipes_rel.waiter_id
     *
     * @param waiterId the value for order_recipes_rel.waiter_id
     *
     * @mbggenerated
     */
    public void setWaiterId(Long waiterId) {
        this.waiterId = waiterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_recipes_rel.takeaway_id
     *
     * @return the value of order_recipes_rel.takeaway_id
     *
     * @mbggenerated
     */
    public Integer getTakeawayId() {
        return takeawayId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_recipes_rel.takeaway_id
     *
     * @param takeawayId the value for order_recipes_rel.takeaway_id
     *
     * @mbggenerated
     */
    public void setTakeawayId(Integer takeawayId) {
        this.takeawayId = takeawayId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_recipes_rel.rel_status
     *
     * @return the value of order_recipes_rel.rel_status
     *
     * @mbggenerated
     */
    public String getRelStatus() {
        return relStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_recipes_rel.rel_status
     *
     * @param relStatus the value for order_recipes_rel.rel_status
     *
     * @mbggenerated
     */
    public void setRelStatus(String relStatus) {
        this.relStatus = relStatus == null ? null : relStatus.trim();
    }
}