package cn.zxf.self.entry;

public class Recipes {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recipes.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recipes.food_name
     *
     * @mbggenerated
     */
    private String foodName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recipes.food_type
     *
     * @mbggenerated
     */
    private Integer foodType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recipes.food_price
     *
     * @mbggenerated
     */
    private Integer foodPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recipes.food_status
     *
     * @mbggenerated
     */
    private Integer foodStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recipes.food_cuisine
     *
     * @mbggenerated
     */
    private String foodCuisine;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recipes.food_key
     *
     * @mbggenerated
     */
    private String foodKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recipes.food_introduce
     *
     * @mbggenerated
     */
    private String foodIntroduce;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recipes.food_img_url
     *
     * @mbggenerated
     */
    private String foodImgUrl;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recipes.id
     *
     * @return the value of recipes.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recipes.id
     *
     * @param id the value for recipes.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recipes.food_name
     *
     * @return the value of recipes.food_name
     *
     * @mbggenerated
     */
    public String getFoodName() {
        return foodName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recipes.food_name
     *
     * @param foodName the value for recipes.food_name
     *
     * @mbggenerated
     */
    public void setFoodName(String foodName) {
        this.foodName = foodName == null ? null : foodName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recipes.food_type
     *
     * @return the value of recipes.food_type
     *
     * @mbggenerated
     */
    public Integer getFoodType() {
        return foodType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recipes.food_type
     *
     * @param foodType the value for recipes.food_type
     *
     * @mbggenerated
     */
    public void setFoodType(Integer foodType) {
        this.foodType = foodType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recipes.food_price
     *
     * @return the value of recipes.food_price
     *
     * @mbggenerated
     */
    public Integer getFoodPrice() {
        return foodPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recipes.food_price
     *
     * @param foodPrice the value for recipes.food_price
     *
     * @mbggenerated
     */
    public void setFoodPrice(Integer foodPrice) {
        this.foodPrice = foodPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recipes.food_status
     *
     * @return the value of recipes.food_status
     *
     * @mbggenerated
     */
    public Integer getFoodStatus() {
        return foodStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recipes.food_status
     *
     * @param foodStatus the value for recipes.food_status
     *
     * @mbggenerated
     */
    public void setFoodStatus(Integer foodStatus) {
        this.foodStatus = foodStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recipes.food_cuisine
     *
     * @return the value of recipes.food_cuisine
     *
     * @mbggenerated
     */
    public String getFoodCuisine() {
        return foodCuisine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recipes.food_cuisine
     *
     * @param foodCuisine the value for recipes.food_cuisine
     *
     * @mbggenerated
     */
    public void setFoodCuisine(String foodCuisine) {
        this.foodCuisine = foodCuisine == null ? null : foodCuisine.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recipes.food_key
     *
     * @return the value of recipes.food_key
     *
     * @mbggenerated
     */
    public String getFoodKey() {
        return foodKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recipes.food_key
     *
     * @param foodKey the value for recipes.food_key
     *
     * @mbggenerated
     */
    public void setFoodKey(String foodKey) {
        this.foodKey = foodKey == null ? null : foodKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recipes.food_introduce
     *
     * @return the value of recipes.food_introduce
     *
     * @mbggenerated
     */
    public String getFoodIntroduce() {
        return foodIntroduce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recipes.food_introduce
     *
     * @param foodIntroduce the value for recipes.food_introduce
     *
     * @mbggenerated
     */
    public void setFoodIntroduce(String foodIntroduce) {
        this.foodIntroduce = foodIntroduce == null ? null : foodIntroduce.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recipes.food_img_url
     *
     * @return the value of recipes.food_img_url
     *
     * @mbggenerated
     */
    public String getFoodImgUrl() {
        return foodImgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recipes.food_img_url
     *
     * @param foodImgUrl the value for recipes.food_img_url
     *
     * @mbggenerated
     */
    public void setFoodImgUrl(String foodImgUrl) {
        this.foodImgUrl = foodImgUrl == null ? null : foodImgUrl.trim();
    }
}