package cn.zxf.self.entry;

public class UserAddressRel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_address_rel.address_id
     *
     * @mbggenerated
     */
    private Long addressId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_address_rel.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_address_rel.oder_address
     *
     * @mbggenerated
     */
    private String oderAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_address_rel.is_first
     *
     * @mbggenerated
     */
    private Integer isFirst;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_address_rel.notes
     *
     * @mbggenerated
     */
    private String notes;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_address_rel.address_id
     *
     * @return the value of user_address_rel.address_id
     *
     * @mbggenerated
     */
    public Long getAddressId() {
        return addressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_address_rel.address_id
     *
     * @param addressId the value for user_address_rel.address_id
     *
     * @mbggenerated
     */
    public void setAddressId(Long addressId) {
        this.addressId = addressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_address_rel.user_id
     *
     * @return the value of user_address_rel.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_address_rel.user_id
     *
     * @param userId the value for user_address_rel.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_address_rel.oder_address
     *
     * @return the value of user_address_rel.oder_address
     *
     * @mbggenerated
     */
    public String getOderAddress() {
        return oderAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_address_rel.oder_address
     *
     * @param oderAddress the value for user_address_rel.oder_address
     *
     * @mbggenerated
     */
    public void setOderAddress(String oderAddress) {
        this.oderAddress = oderAddress == null ? null : oderAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_address_rel.is_first
     *
     * @return the value of user_address_rel.is_first
     *
     * @mbggenerated
     */
    public Integer getIsFirst() {
        return isFirst;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_address_rel.is_first
     *
     * @param isFirst the value for user_address_rel.is_first
     *
     * @mbggenerated
     */
    public void setIsFirst(Integer isFirst) {
        this.isFirst = isFirst;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_address_rel.notes
     *
     * @return the value of user_address_rel.notes
     *
     * @mbggenerated
     */
    public String getNotes() {
        return notes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_address_rel.notes
     *
     * @param notes the value for user_address_rel.notes
     *
     * @mbggenerated
     */
    public void setNotes(String notes) {
        this.notes = notes == null ? null : notes.trim();
    }
}