package cn.zxf.self.bussiness;


import cn.zxf.self.entry.ManageSystem;

public interface ManageSystemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manage_system
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long manageSystemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manage_system
     *
     * @mbggenerated
     */
    int insert(ManageSystem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manage_system
     *
     * @mbggenerated
     */
    int insertSelective(ManageSystem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manage_system
     *
     * @mbggenerated
     */
    ManageSystem selectByPrimaryKey(Long manageSystemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manage_system
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ManageSystem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manage_system
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ManageSystem record);
}