package cn.zxf.self.mapper;

import java.util.List;

import cn.zxf.self.entry.ManageSystem;
import cn.zxf.self.entry.ManageSystemExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Service;

@Mapper
public interface ManageSystemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manage_system
     *
     * @mbggenerated
     */
    int countByExample(ManageSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manage_system
     *
     * @mbggenerated
     */
    int deleteByExample(ManageSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manage_system
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long manageSystemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manage_system
     *
     * @mbggenerated
     */
    int insert(ManageSystem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manage_system
     *
     * @mbggenerated
     */
    int insertSelective(ManageSystem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manage_system
     *
     * @mbggenerated
     */
    List<ManageSystem> selectByExample(ManageSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manage_system
     *
     * @mbggenerated
     */
    ManageSystem selectByPrimaryKey(Long manageSystemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manage_system
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ManageSystem record, @Param("example") ManageSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manage_system
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ManageSystem record, @Param("example") ManageSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manage_system
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ManageSystem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manage_system
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ManageSystem record);
}