package cn.zxf.self.mapper;

import cn.zxf.self.entry.ManageUser;
import cn.zxf.self.entry.ManageUserExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Mapper
public interface ManageUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manage_user
     *
     * @mbggenerated
     */
    int countByExample(ManageUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manage_user
     *
     * @mbggenerated
     */
    int deleteByExample(ManageUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manage_user
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long manageUserId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manage_user
     *
     * @mbggenerated
     */
    int insert(ManageUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manage_user
     *
     * @mbggenerated
     */
    int insertSelective(ManageUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manage_user
     *
     * @mbggenerated
     */
    List<ManageUser> selectByExample(ManageUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manage_user
     *
     * @mbggenerated
     */
    ManageUser selectByPrimaryKey(Long manageUserId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manage_user
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ManageUser record, @Param("example") ManageUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manage_user
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ManageUser record, @Param("example") ManageUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manage_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ManageUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manage_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ManageUser record);
}