package cn.zxf.self.mapper;


import cn.zxf.self.entry.ManageGroup;

public interface ManageGroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manage_group
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long manageGroupId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manage_group
     *
     * @mbggenerated
     */
    int insert(ManageGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manage_group
     *
     * @mbggenerated
     */
    int insertSelective(ManageGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manage_group
     *
     * @mbggenerated
     */
    ManageGroup selectByPrimaryKey(Long manageGroupId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manage_group
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ManageGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manage_group
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ManageGroup record);
}