package cn.zxf.self.mapper;


import cn.zxf.self.entry.ManageUser;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface ManageUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manage_user
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long manageUserId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manage_user
     *
     * @mbggenerated
     */
    int insert(ManageUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manage_user
     *
     * @mbggenerated
     */
    int insertSelective(ManageUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manage_user
     *
     * @mbggenerated
     */
    ManageUser selectByPrimaryKey(Long manageUserId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manage_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ManageUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manage_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ManageUser record);
}