package cn.zxf.self.mapper;


import cn.zxf.self.entry.ManageRoleFuncRel;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface ManageRoleFuncRelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manage_role_func_rel
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long manageRoleFuncRelId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manage_role_func_rel
     *
     * @mbggenerated
     */
    int insert(ManageRoleFuncRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manage_role_func_rel
     *
     * @mbggenerated
     */
    int insertSelective(ManageRoleFuncRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manage_role_func_rel
     *
     * @mbggenerated
     */
    ManageRoleFuncRel selectByPrimaryKey(Long manageRoleFuncRelId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manage_role_func_rel
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ManageRoleFuncRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manage_role_func_rel
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ManageRoleFuncRel record);
}