package cn.zxf.self.mapper;

import java.util.List;

import cn.zxf.self.entry.ManageRole;
import cn.zxf.self.entry.ManageRoleExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface ManageRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manage_role
     *
     * @mbggenerated
     */
    int countByExample(ManageRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manage_role
     *
     * @mbggenerated
     */
    int deleteByExample(ManageRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manage_role
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long manageRoleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manage_role
     *
     * @mbggenerated
     */
    int insert(ManageRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manage_role
     *
     * @mbggenerated
     */
    int insertSelective(ManageRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manage_role
     *
     * @mbggenerated
     */
    List<ManageRole> selectByExample(ManageRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manage_role
     *
     * @mbggenerated
     */
    ManageRole selectByPrimaryKey(Long manageRoleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manage_role
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ManageRole record, @Param("example") ManageRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manage_role
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ManageRole record, @Param("example") ManageRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manage_role
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ManageRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manage_role
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ManageRole record);
}