package cn.zxf.self.mapper;


import cn.zxf.self.entry.ManageRole;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface ManageRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manage_role
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long manageRoleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manage_role
     *
     * @mbggenerated
     */
    int insert(ManageRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manage_role
     *
     * @mbggenerated
     */
    int insertSelective(ManageRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manage_role
     *
     * @mbggenerated
     */
    ManageRole selectByPrimaryKey(Long manageRoleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manage_role
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ManageRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manage_role
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ManageRole record);
}