package cn.zxf.self.mapper;


import cn.zxf.self.entry.ManageUserRoleRel;
import org.apache.ibatis.annotations.Mapper;


@Mapper
public interface ManageUserRoleRelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manage_user_role_rel
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long manageUserRoleRelId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manage_user_role_rel
     *
     * @mbggenerated
     */
    int insert(ManageUserRoleRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manage_user_role_rel
     *
     * @mbggenerated
     */
    int insertSelective(ManageUserRoleRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manage_user_role_rel
     *
     * @mbggenerated
     */
    ManageUserRoleRel selectByPrimaryKey(Long manageUserRoleRelId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manage_user_role_rel
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ManageUserRoleRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manage_user_role_rel
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ManageUserRoleRel record);
}