package cn.zxf.self.mapper;

import cn.zxf.self.entry.ManageFunc;
import cn.zxf.self.example.ManageFuncExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface ManageFuncMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manage_func
     *
     * @mbggenerated
     */
    int countByExample(ManageFuncExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manage_func
     *
     * @mbggenerated
     */
    int deleteByExample(ManageFuncExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manage_func
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long manageFuncId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manage_func
     *
     * @mbggenerated
     */
    int insert(ManageFunc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manage_func
     *
     * @mbggenerated
     */
    int insertSelective(ManageFunc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manage_func
     *
     * @mbggenerated
     */
    List<ManageFunc> selectByExample(ManageFuncExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manage_func
     *
     * @mbggenerated
     */
    ManageFunc selectByPrimaryKey(Long manageFuncId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manage_func
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ManageFunc record, @Param("example") ManageFuncExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manage_func
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ManageFunc record, @Param("example") ManageFuncExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manage_func
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ManageFunc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manage_func
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ManageFunc record);
}