package cn.zxf.self.mapper;

import java.util.List;

import cn.zxf.self.entry.Recipes;
import cn.zxf.self.entry.RecipesExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface RecipesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recipes
     *
     * @mbggenerated
     */
    int countByExample(RecipesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recipes
     *
     * @mbggenerated
     */
    int deleteByExample(RecipesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recipes
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recipes
     *
     * @mbggenerated
     */
    int insert(Recipes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recipes
     *
     * @mbggenerated
     */
    int insertSelective(Recipes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recipes
     *
     * @mbggenerated
     */
    List<Recipes> selectByExample(RecipesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recipes
     *
     * @mbggenerated
     */
    Recipes selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recipes
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Recipes record, @Param("example") RecipesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recipes
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Recipes record, @Param("example") RecipesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recipes
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Recipes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recipes
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Recipes record);
}